sonar.projectKey=personal_finance
sonar.projectName=Personal Finance
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,test/**/*.ts
sonar.exclusions=**/node_modules/**,dist/**,prisma/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info
